// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package pgstore

import (
	"context"
)

const getRoom = `-- name: GetRoom :one
SELECT
  "id", "theme"
FROM rooms
WHERE "theme" = $1
`

func (q *Queries) GetRoom(ctx context.Context, theme string) (Room, error) {
	row := q.db.QueryRow(ctx, getRoom, theme)
	var i Room
	err := row.Scan(&i.ID, &i.Theme)
	return i, err
}
